# Pokemon

### Introduction:

This time you will create the data.



### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Create a data dictionary that looks like the DataFrame below

In [2]:
raw_data = {
    'evolution': ['Ivysaur', 'Charmeleon', 'Wartortle', 'Metapod'],
    'hp': [45, 39, 44, 45],
    'name': ['Bulbasaur', 'Charmander', 'Squirtle', 'Caterpie'],
    'pokedex': ['yes', 'no', 'yes', 'no'],
    'type': ['grass', 'fire', 'water', 'bug']
}

### Step 3. Assign it to a variable called pokemon

In [3]:
pokemon = pd.DataFrame(raw_data)
pokemon

    evolution  hp        name pokedex   type
0     Ivysaur  45   Bulbasaur     yes  grass
1  Charmeleon  39  Charmander      no   fire
2   Wartortle  44    Squirtle     yes  water
3     Metapod  45    Caterpie      no    bug

### Step 4. Ops...it seems the DataFrame columns are in alphabetical order. Place  the order of the columns as name, type, hp, evolution, pokedex

In [4]:
pokemon = pokemon[['name', 'type', 'hp', 'evolution', 'pokedex']]
pokemon

         name   type  hp   evolution pokedex
0   Bulbasaur  grass  45     Ivysaur     yes
1  Charmander   fire  39  Charmeleon      no
2    Squirtle  water  44   Wartortle     yes
3    Caterpie    bug  45     Metapod      no

### Step 5. Add another column called place, and insert what you have in mind.

In [5]:
pokemon['place'] = ['forest', 'volcano', 'sea', 'meadow']
pokemon

C:\Users\Admin\AppData\Local\Temp\ipykernel_12832\3538475271.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pokemon['place'] = ['forest', 'volcano', 'sea', 'meadow']

         name   type  hp   evolution pokedex    place
0   Bulbasaur  grass  45     Ivysaur     yes   forest
1  Charmander   fire  39  Charmeleon      no  volcano
2    Squirtle  water  44   Wartortle     yes      sea
3    Caterpie    bug  45     Metapod      no   meadow

### Step 6. Present the type of each column

In [6]:
pokemon.dtypes

name         object
type         object
hp            int64
evolution    object
pokedex      object
place        object
dtype: object

### BONUS: Create your own question and answer it.

In [7]:
pokemon.describe(include='all')

             name   type         hp evolution pokedex   place
count           4      4   4.000000         4       4       4
unique          4      4        NaN         4       2       4
top     Bulbasaur  grass        NaN   Ivysaur     yes  forest
freq            1      1        NaN         1       2       1
mean          NaN    NaN  43.250000       NaN     NaN     NaN
std           NaN    NaN   2.872281       NaN     NaN     NaN
min           NaN    NaN  39.000000       NaN     NaN     NaN
25%           NaN    NaN  42.750000       NaN     NaN     NaN
50%           NaN    NaN  44.500000       NaN     NaN     NaN
75%           NaN    NaN  45.000000       NaN     NaN     NaN
max           NaN    NaN  45.000000       NaN     NaN     NaN