# Iris

### Introduction:

This exercise may seem a little bit strange, but keep doing it.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data).

### Step 3. Assign it to a variable called iris

In [2]:
iris = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data', header=None)

### Step 4. Create columns for the dataset

In [3]:
iris.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
iris.head()

   sepal_length  sepal_width  petal_length  petal_width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

### Step 5.  Is there any missing value in the dataframe?

In [4]:
iris.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
class           0
dtype: int64

### Step 6.  Lets set the values of the rows 10 to 29 of the column 'petal_length' to NaN

In [5]:
iris.loc[10:29, 'petal_length'] = np.nan

### Step 7. Good, now lets substitute the NaN values to 1.0

In [6]:
iris['petal_length'] = iris['petal_length'].fillna(1.0)

### Step 8. Now let's delete the column class

In [7]:
iris = iris.drop('class', axis=1)

### Step 9.  Set the first 3 rows as NaN

In [8]:
iris.iloc[0:3] = np.nan

### Step 10.  Delete the rows that have NaN

In [9]:
iris = iris.dropna(how='any')
print(f"Rows remaining: {len(iris)}")

Rows remaining: 147

### Step 11. Reset the index so it begins with 0 again

In [10]:
iris = iris.reset_index(drop=True)
iris.head()

   sepal_length  sepal_width  petal_length  petal_width
0           4.6          3.1           1.5          0.2
1           5.0          3.6           1.4          0.2
2           5.4          3.9           1.7          0.4
3           4.6          3.4           1.4          0.3
4           5.0          3.4           1.5          0.2

### BONUS: Create your own question and answer it.

In [11]:
# Question: What is the average sepal length and width after all deletions?
print(f"Average sepal_length: {iris['sepal_length'].mean():.4f}")
print(f"Average sepal_width: {iris['sepal_width'].mean():.4f}")
print(f"Average petal_length: {iris['petal_length'].mean():.4f}")
print(f"Average petal_width: {iris['petal_width'].mean():.4f}")

Average sepal_length: 5.8626
Average sepal_width: 3.0503
Average petal_length: 3.7415
Average petal_width: 1.2190